name: pFact
author: biri
main: snc.pFact.Main
version: 0.1
api-version: 1.13
depend: [ProtocolLib]
commands:
  klan:
    description: use command
    usage: /<command> <event> <arg2> <arg3>
  claim:
    description: use command
    usage: /<command> <claim name/list> <configure/shard/item> <get/set> <value>