name: pFact
author: biri
main: snc.pFact.Main
version: 0.1
api-version: 1.12.2
depend: [ProtocolLib, ZinUtils]
commands:
  klan:
    description: use command
    usage: /<command> <event> <arg2> <arg3>
  claim:
    description: use command
    usage: /<command> <items/claim name/list> <configure/shard/block> <get/set> <value>
  upgrade:
    description: use command
    usage: /<command> <upgrade name/list> <configure/item> <get/set> <value>