name: pFact
author: biri
main: snc.pFact.Main
version: 0.1
api-version: 1.13
commands:
  klan:
    description: use command
    usage: /<command> <event> <arg2> <arg3>
  param:
    description: use command
    usage: /<command>